package scanner;

public enum Type {
	// Token Types
	LPAREN, RPAREN, IDENTIFIER, BOOL, CHAR, NUMBER, OPENRD, CLOSERD, OPENSQ, CLOSESQ, OPENCU, CLOSECU, LAMBDA, DEFINE,
	LET, COND, IF, BEGIN, QUOTE, CHARLITERAL;
}
